---
# defaults file for provision_worker
dir_code: /home/{{ ansible_ssh_user }}/code/
dir_venv: /home/{{ ansible_ssh_user }}/workers_local/
dir_run: /var/local/
dir_run_akara: "{{ dir_run }}akara"
dir_run_rqworker: "{{ dir_run }}rqworker"
# put here so root shuddown finds easily
dir_bin: /usr/local/bin/

akara_port: 8889
akara_log_level: ERROR
akara_alert_to: x@example.edu
akara_alert_from: y@example.edu

redis_host: <from include>
redis_port: 6379
redis_password: <vaulted>
redis_connect_timeout: 10

solr_url: <from include>

couchdb_url: <from include>
couchdb_log_level: INFO
couchdb_username: <vaulted>
couchdb_password: <vaulted>
couchdb_item_database: ucldc
couchdb_dasboard_database: dashboard
couchdb_views_directory: "{{ dir_code }}dpla/ingestion/couchdb_views/"

geonames_username: <vaulted>
geonames_token: <vaulted>
bing_api_key: <vaulted>

email_return_address: ucldc@example.edu
email_sys_admins: x@example.edu,y@example.edu
dpla_config_file: "{{ dir_code }}dpla/ingestion/akara.ini"
