---
# tasks file for create_worker_instance
- name: create a new worker instance in the private vpc
  local_action:
    module: ec2
    count: "{{ count }}"
    state: present
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ image_hvm }}"
    instance_type: "{{ instance_type }}"
    group_id: [ "{{ sec_grp_ingest_private_id }}" ]
    wait: true
    wait_timeout: 500
    vpc_subnet_id: "{{ subnet_id_private }}"
    instance_tags:
        project: "{{ tag_project }}"
        subproject: "{{ tag_subproject }}"
        Name: "{{ name_env}}-worker"
    volumes:
    - device_name: /dev/xvda
      device_type: gp2
      volume_size: 8
      delete_on_termination: yes
  register: ec2_worker
# http://codepoets.co.uk/2014/ansible-random-things/
- name: clear previous instance ips if they match
  local_action: command  ssh-keygen -f "~/.ssh/known_hosts" -R {{ item.private_ip }}  
  with_items: ec2_worker.instances
- debug: var=ec2_worker
- name: Wait for SSH to come up
  wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
  with_items: ec2_worker.instances
