---
# tasks file for create_worker_instance
- debug: var=worker_instance_type
- name: create a new worker ON-DEMAND instance in the private vpc
  local_action:
    module: ec2
    count: "{{ count }}"
    state: present
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ image_hvm }}"
    instance_type: "{{ worker_instance_type }}"
    instance_profile_name: ingest-worker
    group_id: [ "{{ sec_grp_ingest_private_id }}" ]
    wait: true
    wait_timeout: 500
    vpc_subnet_id: "{{ subnet_id_private }}"
    instance_tags:
        project: "{{ tag_project }}"
        subproject: "{{ tag_subproject }}"
        Name: "{{ name_env}}-worker"
        Program: dsc
        Environment: stg
        Service: calisphere
    volumes:
    - device_name: /dev/xvda
      device_type: gp2
      volume_size: 8
      delete_on_termination: yes
  register: ec2_info
  tags: ondemand
- include: check_ssh.yml
