---
- name: grab harvester code for install
  git:
    repo: https://github.com/ucldc/harvester
    dest: "/home/{{ role_user}}/tmp/harvester"
- name: install harvester code
  shell: /home/{{ role_user }}/python2/bin/python setup.py install
  args:
    chdir: "/home/{{ role_user}}/tmp/harvester"
- name: copy relevant scripts
  copy:
    remote_src: yes
    mode: u+rx
    dest: "/home/{{ role_user }}/bin/{{ item }}"
    src: "/home/{{ role_user }}/tmp/harvester/scripts/{{ item }}"
  with_items:
    - delete_couchdb_collection.py
    - delete_couchdb_id_list.py
    - delete_solr_collection.sh
    - queue_image_harvest.py
    - queue_harvest.py
    - queue_sync_couchdb_collection.py
    - sync_couch_collection_to_solr.py
    - sync_solr_documents.py
- name: copy index grab to s3 playbook
  copy:
    remote_src: yes
    mode: u+rx
    dest: "/home/{{ role_user }}/bin/{{ item }}"
    src: "/home/{{ role_user }}/tmp/harvester/harvester/{{ item }}"
  with_items:
    - grab-solr-index-playbook.yml
  when: data_branch == "production"
- name: install redis delete into stage env
  copy:
    remote_src: yes
    mode: u+rx
    dest: "/home/{{ role_user }}/bin/{{ item }}"
    src: "/home/{{ role_user }}/tmp/harvester/scripts/{{ item }}"
  with_items:
    - redis_delete_harvested_images_script.py
  when: data_branch == "stage"
