DATA_BRANCH: production

redis_host: x-001.swle7i.0001.usw2.cache.amazonaws.com
redis_port: 6379
redis_password: "{{ redis_password_prod }}"
redis_connect_timeout: 10

solr_url: http://10.60.39.243:8983/solr/dc-collection

couchdb_url: http://10.60.41.14:5984
couchdb_username: "{{ couchdb_username_prod }}"
couchdb_password: "{{ couchdb_password_prod }}"

run_dir_solr: solr-update
run_dir_rq: rqworker
run_dir_akara: akara-run-dir
