---
# tasks file for solr5_docker
- name: install git
  yum: pkg=git state=present
- name: get the solr_api code
  git:
    repo: "{{ repo_solr }}"
    dest: "{{ dir_code }}"
    update: yes
- name: create data shared directory and set permissions
  file:
    path: /opt/solr/data
    state: directory
    mode: 0777
- name: docker build the image
  become: yes
  docker_image: name={{ docker_image_name }} path={{ dir_code }} state=present
- name: docker run the image with appropriate flags
  become: yes
  docker_container: 
    name: solr
    image: "{{ docker_image_name }}"
    ports: 8983:8983
    state: started
    restart_policy: always
    volumes: /opt/solr/data/:/opt/solr/server/solr/dc-collection/data:rw
